### ISSUE TITLE
[question] network /  wifi info - Interfaces

### ISSUE THREAD

**Issue by gbdomubpkm** [walking-octopus/system-info-ut#4]
Is it normal to see that (Volla ) ? 
Info shown when wifi is on and connected to a hotspot 
![screenshot20220911_182721074](https://user-images.githubusercontent.com/50362604/189593853-967eda8c-2fda-4b68-abdf-efbe0ed4e04a.png)

**Comment by aparatext** [comment]
It says you aren't connected to any networks on any interfaces. Also, thanks for sharing this screenshot, so I can filter out more virtual network interfaces. Since the app works as expected, I'll close this issue. If you think it's wrong, run `nmcli device status` to manually check it. If it matches, the app works as expected.

**Comment by gbdomubpkm** [comment]
In this example, i'm connected to a hotspot and i see wifi Status Inactive if if understand well. Is it normal ?

In an other case, when cellular data are on, it shows ril_O status inactive wheareas it shoud be shown active i think. 
I saw these info with nmcli device status.
Interface / Status are exact with your smartphone ?

**Comment by aparatext** [comment]
> Interface statuses are exact with your smartphone?

On my Nexus 5, it reflects what interfaces are toggled on/off in the indicator panel.
