### ISSUE TITLE
No codename

### ISSUE THREAD

**Issue by gbdomubpkm** [walking-octopus/system-info-ut#8]
What's about codename ?
![screenshot20220929_113251545](https://user-images.githubusercontent.com/50362604/192997791-1546d0ac-0a81-4772-9d7e-93e3785dd0ec.png)

**Comment by aparatext** [comment]
It couldn't find a build property with for it. Its codename is supposed to be `volla-yggdrasil`. Can you run `getprop | grep volla-yggdrasil` and share the output, so I can check if it's ever present in the build props?

**Comment by gbdomubpkm** [comment]
Where should be the output ? In terminal, the output give nothing.

I found : there is an output, if i put only 
   `getprop | grep yggdrasil`
![screenshot20220929_220110035](https://user-images.githubusercontent.com/50362604/193131354-eb076f03-70f2-4e3b-94d9-e4f61c7bef9e.png)
.

**Comment by aparatext** [comment]
Fixed!
I was fetching a less common property `ro.cm.device` that wasn't present on some devices, instead of `ro.build.product`.
It will be included in the next release, but if you don't want to wait, download the latest build [here](https://github.com/walking-octopus/system-info-ut/actions/runs/3156577143).
Thanks for bringing this to my attention!

**Comment by gbdomubpkm** [comment]
I confirm that's ok. Thanks
![screenshot20220930_161207687](https://user-images.githubusercontent.com/50362604/193289360-689cfe3d-78c7-49db-a7f2-e120b748d7b8.png)
